apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'argocd-example'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
